# Generated by Django 4.1.7 on 2023-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['price'], 'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AddField(
            model_name='phone',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Phone date'),
        ),
    ]
