# Generated by Django 4.1.7 on 2023-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_phone_options_phone_check_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='about',
            field=models.TextField(null=True, verbose_name='Phone about'),
        ),
    ]
