# Generated by Django 4.1.7 on 2023-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='check_1',
            field=models.BooleanField(null=True, verbose_name='Yes/No'),
        ),
    ]
